'use client';

import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from '@/app/components/ui/select';
import { useState } from 'react';

const EuropeanCountriesArray = [
  {
    id: 225,
    name: 'Türkiye',
    iso3: 'TUR',
    iso2: 'TR',
    numeric_code: '792',
    phone_code: 90,
    capital: 'Ankara',
    currency: 'TRY',
    currency_name: 'Turkish lira',
    currency_symbol: '₺',
    tld: '.tr',
    native: 'Türkiye',
    region: 'Asia',
    subregion: 'Western Asia',
    latitude: '39.00000000',
    longitude: '35.00000000',
    emoji: '🇹🇷',
  },
  {
    id: 1,
    name: 'Arnavutluk',
    iso3: 'ALB',
    iso2: 'AL',
    numeric_code: '008',
    phone_code: 355,
    capital: 'Tirana',
    currency: 'ALL',
    currency_name: 'Albanian lek',
    currency_symbol: 'L',
    tld: '.al',
    native: 'Shqipëri',
    region: 'Europe',
    subregion: 'Southern Europe',
    latitude: '41.1533',
    longitude: '20.1683',
    emoji: '🇦🇱',
  },
  {
    id: 2,
    name: 'Andorra',
    iso3: 'AND',
    iso2: 'AD',
    numeric_code: '020',
    phone_code: 376,
    capital: 'Andorra la Vella',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.ad',
    native: 'Andorra',
    region: 'Europe',
    subregion: 'Western Europe',
    latitude: '42.5063',
    longitude: '1.5211',
    emoji: '🇦🇩',
  },
  {
    id: 3,
    name: 'Ermenistan',
    iso3: 'ARM',
    iso2: 'AM',
    numeric_code: '051',
    phone_code: 374,
    capital: 'Yerevan',
    currency: 'AMD',
    currency_name: 'Armenian dram',
    currency_symbol: '֏',
    tld: '.am',
    native: 'Հայաստան',
    region: 'Asia',
    subregion: 'Western Asia',
    latitude: '40.0691',
    longitude: '45.0382',
    emoji: '🇦🇲',
  },
  {
    id: 4,
    name: 'Avusturya',
    iso3: 'AUT',
    iso2: 'AT',
    numeric_code: '040',
    phone_code: 43,
    capital: 'Vienna',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.at',
    native: 'Österreich',
    region: 'Europe',
    subregion: 'Western Europe',
    latitude: '47.3539',
    longitude: '13.2904',
    emoji: '🇦🇹',
  },
  {
    id: 5,
    name: 'Azerbaycan',
    iso3: 'AZE',
    iso2: 'AZ',
    numeric_code: '031',
    phone_code: 994,
    capital: 'Baku',
    currency: 'AZN',
    currency_name: 'Azerbaijani manat',
    currency_symbol: '₼',
    tld: '.az',
    native: 'Azərbaycan',
    region: 'Asia',
    subregion: 'Western Asia',
    latitude: '40.1431',
    longitude: '47.5769',
    emoji: '🇦🇿',
  },
  {
    id: 6,
    name: 'Belarus',
    iso3: 'BLR',
    iso2: 'BY',
    numeric_code: '112',
    phone_code: 375,
    capital: 'Minsk',
    currency: 'BYN',
    currency_name: 'Belarusian ruble',
    currency_symbol: 'Br',
    tld: '.by',
    native: 'Беларусь',
    region: 'Europe',
    subregion: 'Eastern Europe',
    latitude: '53.9006',
    longitude: '27.5590',
    emoji: '🇧🇾',
  },
  {
    id: 7,
    name: 'Belçika',
    iso3: 'BEL',
    iso2: 'BE',
    numeric_code: '056',
    phone_code: 32,
    capital: 'Brussels',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.be',
    native: 'België',
    region: 'Europe',
    subregion: 'Western Europe',
    latitude: '50.8503',
    longitude: '4.3517',
    emoji: '🇧🇪',
  },
  {
    id: 8,
    name: 'Bosna Hersek',
    iso3: 'BIH',
    iso2: 'BA',
    numeric_code: '070',
    phone_code: 387,
    capital: 'Sarajevo',
    currency: 'BAM',
    currency_name: 'Bosnia and Herzegovina convertible mark',
    currency_symbol: 'KM',
    tld: '.ba',
    native: 'Bosna i Hercegovina',
    region: 'Europe',
    subregion: 'Southern Europe',
    latitude: '43.8486',
    longitude: '18.3564',
    emoji: '🇧🇦',
  },
  {
    id: 9,
    name: 'Bulgaristan',
    iso3: 'BGR',
    iso2: 'BG',
    numeric_code: '100',
    phone_code: 359,
    capital: 'Sofia',
    currency: 'BGN',
    currency_name: 'Bulgarian lev',
    currency_symbol: 'лв',
    tld: '.bg',
    native: 'България',
    region: 'Europe',
    subregion: 'Eastern Europe',
    latitude: '42.7339',
    longitude: '25.4858',
    emoji: '🇧🇬',
  },
  {
    id: 10,
    name: 'Hırvatistan',
    iso3: 'HRV',
    iso2: 'HR',
    numeric_code: '191',
    phone_code: 385,
    capital: 'Zagreb',
    currency: 'HRK',
    currency_name: 'Croatian kuna',
    currency_symbol: 'kn',
    tld: '.hr',
    native: 'Hrvatska',
    region: 'Europe',
    subregion: 'Southern Europe',
    latitude: '45.1000',
    longitude: '15.2000',
    emoji: '🇭🇷',
  },
  {
    id: 11,
    name: 'Kıbrıs',
    iso3: 'CYP',
    iso2: 'CY',
    numeric_code: '196',
    phone_code: 357,
    capital: 'Nicosia',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.cy',
    native: 'Κύπρος',
    region: 'Europe',
    subregion: 'Southern Europe',
    latitude: '35.1667',
    longitude: '33.3667',
    emoji: '🇨🇾',
  },
  {
    id: 12,
    name: 'Çek Cumhuriyeti',
    iso3: 'CZE',
    iso2: 'CZ',
    numeric_code: '203',
    phone_code: 420,
    capital: 'Prague',
    currency: 'CZK',
    currency_name: 'Czech koruna',
    currency_symbol: 'Kč',
    tld: '.cz',
    native: 'Česká republika',
    region: 'Europe',
    subregion: 'Central Europe',
    latitude: '50.0755',
    longitude: '14.4378',
    emoji: '🇨🇿',
  },
  {
    id: 13,
    name: 'Danimarka',
    iso3: 'DNK',
    iso2: 'DK',
    numeric_code: '208',
    phone_code: 45,
    capital: 'Copenhagen',
    currency: 'DKK',
    currency_name: 'Danish krone',
    currency_symbol: 'kr',
    tld: '.dk',
    native: 'Danmark',
    region: 'Europe',
    subregion: 'Northern Europe',
    latitude: '55.6761',
    longitude: '12.5683',
    emoji: '🇩🇰',
  },
  {
    id: 14,
    name: 'Estonya',
    iso3: 'EST',
    iso2: 'EE',
    numeric_code: '233',
    phone_code: 372,
    capital: 'Tallinn',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.ee',
    native: 'Eesti',
    region: 'Europe',
    subregion: 'Northern Europe',
    latitude: '59.4372',
    longitude: '24.7536',
    emoji: '🇪🇪',
  },
  {
    id: 15,
    name: 'Finlandiya',
    iso3: 'FIN',
    iso2: 'FI',
    numeric_code: '246',
    phone_code: 358,
    capital: 'Helsinki',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.fi',
    native: 'Suomi',
    region: 'Europe',
    subregion: 'Northern Europe',
    latitude: '60.1695',
    longitude: '24.9354',
    emoji: '🇫🇮',
  },
  {
    id: 16,
    name: 'Fransa',
    iso3: 'FRA',
    iso2: 'FR',
    numeric_code: '250',
    phone_code: 33,
    capital: 'Paris',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.fr',
    native: 'France',
    region: 'Europe',
    subregion: 'Western Europe',
    latitude: '46.6034',
    longitude: '1.8883',
    emoji: '🇫🇷',
  },
  {
    id: 17,
    name: 'Gürcistan',
    iso3: 'GEO',
    iso2: 'GE',
    numeric_code: '268',
    phone_code: 995,
    capital: 'Tbilisi',
    currency: 'GEL',
    currency_name: 'Georgian lari',
    currency_symbol: '₾',
    tld: '.ge',
    native: 'საქართველო',
    region: 'Asia',
    subregion: 'Western Asia',
    latitude: '42.3154',
    longitude: '43.9991',
    emoji: '🇬🇪',
  },
  {
    id: 18,
    name: 'Almanya',
    iso3: 'DEU',
    iso2: 'DE',
    numeric_code: '276',
    phone_code: 49,
    capital: 'Berlin',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.de',
    native: 'Deutschland',
    region: 'Europe',
    subregion: 'Western Europe',
    latitude: '51.1657',
    longitude: '10.4515',
    emoji: '🇩🇪',
  },
  {
    id: 19,
    name: 'Yunanistan',
    iso3: 'GRC',
    iso2: 'GR',
    numeric_code: '300',
    phone_code: 30,
    capital: 'Athens',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.gr',
    native: 'Ελλάδα',
    region: 'Europe',
    subregion: 'Southern Europe',
    latitude: '39.0742',
    longitude: '21.8243',
    emoji: '🇬🇷',
  },
  {
    id: 20,
    name: 'Macaristan',
    iso3: 'HUN',
    iso2: 'HU',
    numeric_code: '348',
    phone_code: 36,
    capital: 'Budapest',
    currency: 'HUF',
    currency_name: 'Hungarian forint',
    currency_symbol: 'Ft',
    tld: '.hu',
    native: 'Magyarország',
    region: 'Europe',
    subregion: 'Central Europe',
    latitude: '47.1625',
    longitude: '19.5033',
    emoji: '🇭🇺',
  },
  {
    id: 21,
    name: 'İzlanda',
    iso3: 'ISL',
    iso2: 'IS',
    numeric_code: '352',
    phone_code: 354,
    capital: 'Reykjavik',
    currency: 'ISK',
    currency_name: 'Icelandic króna',
    currency_symbol: 'kr',
    tld: '.is',
    native: 'Ísland',
    region: 'Europe',
    subregion: 'Northern Europe',
    latitude: '64.9631',
    longitude: '-19.0208',
    emoji: '🇮🇸',
  },
  {
    id: 22,
    name: 'İrlanda',
    iso3: 'IRL',
    iso2: 'IE',
    numeric_code: '372',
    phone_code: 353,
    capital: 'Dublin',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.ie',
    native: 'Éire',
    region: 'Europe',
    subregion: 'Northern Europe',
    latitude: '53.4129',
    longitude: '-8.2439',
    emoji: '🇮🇪',
  },
  {
    id: 23,
    name: 'İtalya',
    iso3: 'ITA',
    iso2: 'IT',
    numeric_code: '380',
    phone_code: 39,
    capital: 'Rome',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.it',
    native: 'Italia',
    region: 'Europe',
    subregion: 'Southern Europe',
    latitude: '41.8719',
    longitude: '12.5674',
    emoji: '🇮🇹',
  },
  {
    id: 25,
    name: 'Letonya',
    iso3: 'LVA',
    iso2: 'LV',
    numeric_code: '428',
    phone_code: 371,
    capital: 'Riga',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.lv',
    native: 'Latvija',
    region: 'Europe',
    subregion: 'Northern Europe',
    latitude: '56.8796',
    longitude: '24.6032',
    emoji: '🇱🇻',
  },
  {
    id: 26,
    name: 'Litvanya',
    iso3: 'LTU',
    iso2: 'LT',
    numeric_code: '440',
    phone_code: 370,
    capital: 'Vilnius',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.lt',
    native: 'Lietuva',
    region: 'Europe',
    subregion: 'Northern Europe',
    latitude: '55.1694',
    longitude: '23.8813',
    emoji: '🇱🇹',
  },
  {
    id: 27,
    name: 'Lüksemburg',
    iso3: 'LUX',
    iso2: 'LU',
    numeric_code: '442',
    phone_code: 352,
    capital: 'Luxembourg City',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.lu',
    native: 'Lëtzebuerg',
    region: 'Europe',
    subregion: 'Western Europe',
    latitude: '49.6118',
    longitude: '6.1319',
    emoji: '🇱🇺',
  },
  {
    id: 28,
    name: 'Malta',
    iso3: 'MLT',
    iso2: 'MT',
    numeric_code: '470',
    phone_code: 356,
    capital: 'Valletta',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.mt',
    native: 'Malta',
    region: 'Europe',
    subregion: 'Southern Europe',
    latitude: '35.9375',
    longitude: '14.3754',
    emoji: '🇲🇹',
  },
  {
    id: 29,
    name: 'Moldova',
    iso3: 'MDA',
    iso2: 'MD',
    numeric_code: '498',
    phone_code: 373,
    capital: 'Chișinău',
    currency: 'MDL',
    currency_name: 'Moldovan leu',
    currency_symbol: 'lei',
    tld: '.md',
    native: 'Moldova',
    region: 'Europe',
    subregion: 'Eastern Europe',
    latitude: '47.4116',
    longitude: '28.3699',
    emoji: '🇲🇩',
  },
  {
    id: 30,
    name: 'Monako',
    iso3: 'MCO',
    iso2: 'MC',
    numeric_code: '492',
    phone_code: 377,
    capital: 'Monaco',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.mc',
    native: 'Monaco',
    region: 'Europe',
    subregion: 'Western Europe',
    latitude: '43.7384',
    longitude: '7.4246',
    emoji: '🇲🇨',
  },
  {
    id: 31,
    name: 'Karadağ',
    iso3: 'MNE',
    iso2: 'ME',
    numeric_code: '499',
    phone_code: 382,
    capital: 'Podgorica',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.me',
    native: 'Crna Gora',
    region: 'Europe',
    subregion: 'Southern Europe',
    latitude: '42.7087',
    longitude: '19.3744',
    emoji: '🇲🇪',
  },
  {
    id: 32,
    name: 'Hollanda',
    iso3: 'NLD',
    iso2: 'NL',
    numeric_code: '528',
    phone_code: 31,
    capital: 'Amsterdam',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.nl',
    native: 'Nederland',
    region: 'Europe',
    subregion: 'Western Europe',
    latitude: '52.1326',
    longitude: '5.2913',
    emoji: '🇳🇱',
  },
  {
    id: 33,
    name: 'Kuzey Makedonya',
    iso3: 'MKD',
    iso2: 'MK',
    numeric_code: '807',
    phone_code: 389,
    capital: 'Skopje',
    currency: 'MKD',
    currency_name: 'Macedonian denar',
    currency_symbol: 'ден',
    tld: '.mk',
    native: 'Северна Македонија',
    region: 'Europe',
    subregion: 'Southern Europe',
    latitude: '41.6086',
    longitude: '21.7453',
    emoji: '🇲🇰',
  },
  {
    id: 34,
    name: 'Norveç',
    iso3: 'NOR',
    iso2: 'NO',
    numeric_code: '578',
    phone_code: 47,
    capital: 'Oslo',
    currency: 'NOK',
    currency_name: 'Norwegian krone',
    currency_symbol: 'kr',
    tld: '.no',
    native: 'Norge',
    region: 'Europe',
    subregion: 'Northern Europe',
    latitude: '60.4720',
    longitude: '8.4689',
    emoji: '🇳🇴',
  },
  {
    id: 35,
    name: 'Polonya',
    iso3: 'POL',
    iso2: 'PL',
    numeric_code: '616',
    phone_code: 48,
    capital: 'Warsaw',
    currency: 'PLN',
    currency_name: 'Polish złoty',
    currency_symbol: 'zł',
    tld: '.pl',
    native: 'Polska',
    region: 'Europe',
    subregion: 'Central Europe',
    latitude: '51.9194',
    longitude: '19.1451',
    emoji: '🇵🇱',
  },
  {
    id: 36,
    name: 'Portekiz',
    iso3: 'PRT',
    iso2: 'PT',
    numeric_code: '620',
    phone_code: 351,
    capital: 'Lisbon',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.pt',
    native: 'Portugal',
    region: 'Europe',
    subregion: 'Southern Europe',
    latitude: '39.3999',
    longitude: '-8.2245',
    emoji: '🇵🇹',
  },
  {
    id: 37,
    name: 'Romanya',
    iso3: 'ROU',
    iso2: 'RO',
    numeric_code: '642',
    phone_code: 40,
    capital: 'Bucharest',
    currency: 'RON',
    currency_name: 'Romanian leu',
    currency_symbol: 'lei',
    tld: '.ro',
    native: 'România',
    region: 'Europe',
    subregion: 'Eastern Europe',
    latitude: '45.9432',
    longitude: '24.9668',
    emoji: '🇷🇴',
  },
  {
    id: 38,
    name: 'Rusya',
    iso3: 'RUS',
    iso2: 'RU',
    numeric_code: '643',
    phone_code: 7,
    capital: 'Moscow',
    currency: 'RUB',
    currency_name: 'Russian ruble',
    currency_symbol: '₽',
    tld: '.ru',
    native: 'Россия',
    region: 'Asia',
    subregion: 'Eastern Asia',
    latitude: '61.5240',
    longitude: '105.3188',
    emoji: '🇷🇺',
  },
  {
    id: 40,
    name: 'Sırbistan',
    iso3: 'SRB',
    iso2: 'RS',
    numeric_code: '688',
    phone_code: 381,
    capital: 'Belgrade',
    currency: 'RSD',
    currency_name: 'Serbian dinar',
    currency_symbol: 'дин.',
    tld: '.rs',
    native: 'Србија',
    region: 'Europe',
    subregion: 'Southern Europe',
    latitude: '44.0165',
    longitude: '21.0059',
    emoji: '🇷🇸',
  },
  {
    id: 41,
    name: 'Slovakya',
    iso3: 'SVK',
    iso2: 'SK',
    numeric_code: '703',
    phone_code: 421,
    capital: 'Bratislava',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.sk',
    native: 'Slovensko',
    region: 'Europe',
    subregion: 'Central Europe',
    latitude: '48.6690',
    longitude: '19.6990',
    emoji: '🇸🇰',
  },
  {
    id: 42,
    name: 'Slovenya',
    iso3: 'SVN',
    iso2: 'SI',
    numeric_code: '705',
    phone_code: 386,
    capital: 'Ljubljana',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.si',
    native: 'Slovenija',
    region: 'Europe',
    subregion: 'Southern Europe',
    latitude: '46.1512',
    longitude: '14.9955',
    emoji: '🇸🇮',
  },
  {
    id: 43,
    name: 'İspanya',
    iso3: 'ESP',
    iso2: 'ES',
    numeric_code: '724',
    phone_code: 34,
    capital: 'Madrid',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.es',
    native: 'España',
    region: 'Europe',
    subregion: 'Southern Europe',
    latitude: '40.4637',
    longitude: '-3.7492',
    emoji: '🇪🇸',
  },
  {
    id: 44,
    name: 'İsveç',
    iso3: 'SWE',
    iso2: 'SE',
    numeric_code: '752',
    phone_code: 46,
    capital: 'Stockholm',
    currency: 'SEK',
    currency_name: 'Swedish krona',
    currency_symbol: 'kr',
    tld: '.se',
    native: 'Sverige',
    region: 'Europe',
    subregion: 'Northern Europe',
    latitude: '60.1282',
    longitude: '18.6435',
    emoji: '🇸🇪',
  },
  {
    id: 45,
    name: 'İsviçre',
    iso3: 'CHE',
    iso2: 'CH',
    numeric_code: '756',
    phone_code: 41,
    capital: 'Bern',
    currency: 'CHF',
    currency_name: 'Swiss franc',
    currency_symbol: 'CHF',
    tld: '.ch',
    native: 'Schweiz',
    region: 'Europe',
    subregion: 'Western Europe',
    latitude: '46.8182',
    longitude: '8.2275',
    emoji: '🇨🇭',
  },
  {
    id: 46,
    name: 'Ukrayna',
    iso3: 'UKR',
    iso2: 'UA',
    numeric_code: '804',
    phone_code: 380,
    capital: 'Kyiv',
    currency: 'UAH',
    currency_name: 'Ukrainian hryvnia',
    currency_symbol: '₴',
    tld: '.ua',
    native: 'Україна',
    region: 'Europe',
    subregion: 'Eastern Europe',
    latitude: '48.3794',
    longitude: '31.1656',
    emoji: '🇺🇦',
  },
  {
    id: 47,
    name: 'Birleşik Krallık',
    iso3: 'GBR',
    iso2: 'GB',
    numeric_code: '826',
    phone_code: 44,
    capital: 'London',
    currency: 'GBP',
    currency_name: 'British pound',
    currency_symbol: '£',
    tld: '.uk',
    native: 'United Kingdom',
    region: 'Europe',
    subregion: 'Northern Europe',
    latitude: '55.3781',
    longitude: '-3.4360',
    emoji: '🇬🇧',
  },
  {
    id: 50,
    name: 'Kosova',
    iso3: 'XKX',
    iso2: 'XK',
    numeric_code: '0',
    phone_code: 383,
    capital: 'Pristina',
    currency: 'EUR',
    currency_name: 'Euro',
    currency_symbol: '€',
    tld: '.xk',
    native: 'Kosovë',
    region: 'Europe',
    subregion: 'Southern Europe',
    latitude: '42.6026',
    longitude: '20.9029',
    emoji: '🇽🇰',
  },
];
export default function CountrySelect({
  setCountry,
}: {
  setCountry: (countryId: number, countryName: string) => void; // Updated signature to accept two arguments
}) {
  const [selectedCountryId, setSelectedCountryId] = useState<
    string | undefined
  >();

  const handleSelectCountry = (value: string) => {
    const selectedCountry = EuropeanCountriesArray.find(
      (c) => c.id.toString() === value
    );
    if (selectedCountry) {
      setSelectedCountryId(value);
      setCountry(selectedCountry.id, selectedCountry.name); // Pass both id and name
    }
  };

  return (
    <Select onValueChange={handleSelectCountry} value={selectedCountryId}>
      <SelectTrigger className='w-full'>
        <SelectValue placeholder='Bir ülke seç' />
      </SelectTrigger>
      <SelectContent>
        <SelectGroup>
          <SelectLabel>Tüm Ülkeler</SelectLabel>
          {EuropeanCountriesArray.sort((a, b) =>
            a.name.localeCompare(b.name)
          ).map((country) => (
            <SelectItem
              key={country.id}
              value={country.id.toString()}
              className='flex items-center'
            >
              <span className='mr-2'>{country.emoji}</span>
              {country.name}
            </SelectItem>
          ))}
        </SelectGroup>
      </SelectContent>
    </Select>
  );
}
